### ISSUE TITLE
urh does not work

### ISSUE THREAD

**Issue by andynoack** [splotz90/urh#22]
_Please use this template for bug reports. If you have a feature request or question just delete everything and write as you like._
## Expected Behavior
urh works

## Actual Behavior
urh does not work

## Steps to Reproduce the Problem

  1. ./main.py

./main.py 
Time for generating UI: 0.01 seconds
Adding /tmp/urh/src to pythonpath. This is only important when running URH from source.
Traceback (most recent call last):
  File "./main.py", line 145, in <module>
    main()
  File "./main.py", line 70, in main
    from urh.controller.MainController import MainController
  File "/tmp/urh/src/urh/controller/MainController.py", line 20, in <module>
    from urh.controller.SimulatorTabController import SimulatorTabController
  File "/tmp/urh/src/urh/controller/SimulatorTabController.py", line 28, in <module>
    from urh.controller.SimulateDialogController import SimulateDialogController
  File "/tmp/urh/src/urh/controller/SimulateDialogController.py", line 6, in <module>
    from urh.ui.delegates.SimulatorSettingsComboBoxDelegate import SimulatorSettingsComboBoxDelegate
  File "/tmp/urh/src/urh/ui/delegates/SimulatorSettingsComboBoxDelegate.py", line 4, in <module>
    from urh.controller.SendRecvSettingsDialogController import SendRecvSettingsDialogController
  File "/tmp/urh/src/urh/controller/SendRecvSettingsDialogController.py", line 4, in <module>
    from urh.ui.ui_send_recv_settings import Ui_SendRecvSettingsDialog
ImportError: No module named 'urh.ui.ui_send_recv_settings'

## Platform Specifications

  - Python Version: 3.4.5
  - Operating System: gentoo
  - Version of URH: 1.6.6

**Comment by splotz90** [comment]
Fixed. Thank you!
